<div class="flash error">
    <?php // エラー内容（例外メッセージ）をそのまま表示 ?>
    <h1><?= h($e->getMessage()) ?></h1>
</div>

<div class="flash valid">
    <?php // 解決方法の案内 ?>
    <h1>解決方法</h1>
    <h4>
        <strong>
            次のファイルに partial（部分テンプレート）を作成してください：<br>
            <em class="file">
                <?= APP_PATH, 'views/_shared/partials/', h(View::getPath()) ?>
            </em>
        </strong>
    </h4>
</div>
