<?php
/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * このソースファイルは、同梱の LICENSE ファイルに記載されている
 * New BSD ライセンスに従います。
 *
 * アプリケーション向け「punbb」スタイルのページネーター
 *
 * ページネーターのパラメータ:
 *   page: ページネーター呼び出しで取得したオブジェクト
 *   show: ページャに表示するページ番号の数
 *   url : ページングを行うアクションのURL。
 *         デフォルトは "module/controller/page/" で、
 *         ページ番号をパラメータとして送る。
 *
 * @category    Kumbia
 * @package     Partials
 * @subpackage  Paginators
 *
 * @copyright  Copyright (c) 2005 - 2023 KumbiaPHP Team (http://www.kumbiaphp.com)
 * @license    https://github.com/KumbiaPHP/KumbiaPHP/blob/master/LICENSE   New BSD License
 */

// URL が指定されていない場合は Router から取得して組み立てる
if (!isset($url)) {
    extract(Router::get());
    $url = "$controller/page";
    if ($module) {
        $url = "$module/$url";
    }
}

// 表示するページ番号の個数が指定されていない場合のデフォルト
if (!isset($show)) {
    $show = 10;
}

$half = floor($show / 2);

// ページャを現在ページを中心に表示するための開始位置を計算
if ($page->current <= $half) {
    $start = 1;
} elseif (($page->total - $page->current) < $half) {
    $start = $page->total - $show + 1;
    if ($start < 1) $start = 1;
} else {
    $start = $page->current - $half;
}
?>

<div class="paginator">
    <?php
    // 前のページへのリンク
    // ページ1の場合はページ番号なしURLでリンクする
    if ($page->prev == 1) {
        echo Html::link(
            "$url/",
            '前へ',
            'title="前のページへ移動" class="nextprev" rel="prev"'
        );
    } elseif ($page->prev) {
        echo Html::link(
            "$url/$page->prev/",
            '前へ',
            'title="前のページへ移動" class="nextprev" rel="prev"'
        );
    }
    ?>

    <?php
    // 先頭ページ付近の処理
    // ページ1は番号なしURLでリンクする
    if ($start == 1) {
        $start = 2;
        $show -= 1;
        echo $page->current == 1
            ? "<strong>1</strong>"
            : Html::link("$url/", '1');
    } elseif ($start > 1) {
        echo Html::link("$url/", "1");
    }
    if ($start > 2): ?>
        ...
    <?php endif; ?>

    <?php for ($i = $start; $i <= $page->total && $i < ($start + $show); $i++): ?>
        <?= $i == $page->current
            ? "<strong>$i</strong>"
            : Html::link("$url/$i/", $i); ?>
    <?php endfor; ?>

    <?php if ($page->total > $i): ?>
        ...
        <?= Html::link("$url/$page->total/", $page->total); ?>
    <?php elseif ($i == $page->total): ?>
        <?= Html::link("$url/$i/", $i); ?>
    <?php endif; ?>

    <?php
    // 次のページへのリンク
    if ($page->next) {
        echo Html::link(
            "$url/$page->next/",
            '次へ',
            'title="次のページへ移動" class="nextprev" rel="next"'
        );
    }
    ?>
</div>
