<div id="scaffold">
<?php View::content()?>
<h1><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
<div class="actions">
    <?= Html::linkAction("crear/", 'レコードを作成', 'class="btn btn-primary"')?>
</div>
<?php if (isset($data->items) && (count($data->items) > 0)) : ?>
<table class="t">
    <thead><tr>
    <?php foreach (current($data->items)->fields as $field) : ?>
        <th><?= (current($data->items)->get_alias($field))?></th>
    <?php endforeach?>
    <th>操作</th>
    </tr></thead>
    <tbody>
    <?php foreach ($data->items as $item) : ?>
        <tr>
            <?php foreach ($item->fields as $field) : ?>
            <td><?= h($item->$field)?></td>
            <?php endforeach?>
            <td>
                <?= Html::linkAction("ver/$item->id", '表示')?> |
                <?= Html::linkAction("editar/$item->id", '編集')?> |
                <?= Html::linkAction(
                    "borrar/$item->id",
                    '削除',
                    'onclick="return confirm(\'本当に削除してもよろしいですか？\')"'
                ) ?>
            </td>
        </tr>
    <?php endforeach?>
    </tbody>
</table>
<?php View::partial('paginators/digg', false, array('page' => $data ,'url' => Router::get('controller_path').'/index')) ?>

<?php else : // レコードが存在しない場合 ?>
<h2>レコードがありません</h2>
<?php endif ?>
</div>
