<div id="scaffold">
<?php View::content()?>
<?php if ($data) : ?>
    <h1><?= ucwords("$model"),": <span>$action_name</span>" ?></h1>
    <ul>
    <?php foreach ($data->fields as $field) : ?>
        <li><strong><?= $data->alias[$field]?> :</strong>  <?= h($data->$field) ?></li>
    <?php endforeach ?>
    </ul>

    <div class="actions">
        <a href="../" class="btn btn-default">一覧</a>
        <a href="../crear/" class="btn btn-primary">レコードを作成</a>
        <a href="../editar/<?= $data->id?>" class="btn btn-warning">編集</a>
        <a class="del btn btn-danger"
           title="本当に削除してもよろしいですか？"
           href="../borrar/<?= $data->id?>"
           onclick="return confirm('本当に削除してもよろしいですか？');">削除</a>
    </div>
<?php else : ?>
    <?php http_response_code(404)?>
    <h1>存在しません</h1>
    <div class="actions">
        <a href="../">一覧</a>
        <a href="../crear/">レコードを作成</a>
    </div>
<?php endif ?>
</div>
